/vis/open OGL
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/set/style surface
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/autoRefresh true

/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/add/hits

/tracking/storeTrajectory 1

# Show all particles, default coloring
#/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set proton green

/vis/viewer/flush

/run/initialize
/run/beamOn 1000

